if(NOT ROOT)
    get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
file(READ "${ROOT}/docs/dd-upstream.json" pin)
string(JSON repository GET "${pin}" repository)
string(JSON revision GET "${pin}" revision)
string(JSON version GET "${pin}" version)
if(NOT repository STREQUAL "https://github.com/ZacWalk/dd" OR
   NOT revision STREQUAL "0a356d82a256b021e9209b26aa198a247ff4f419" OR
   NOT version STREQUAL "0.2.0")
    message(FATAL_ERROR "Unexpected upstream dd release")
endif()
file(GLOB_RECURSE runtime RELATIVE "${ROOT}" "${ROOT}/.dd/*")
list(FILTER runtime EXCLUDE REGEX "^\\.dd/state/")
list(APPEND runtime "dd.ps1")
list(SORT runtime)
string(JSON count LENGTH "${pin}" files)
math(EXPR last "${count} - 1")
set(pinned)
foreach(index RANGE ${last})
    string(JSON path MEMBER "${pin}" files ${index})
    string(JSON expected GET "${pin}" files "${path}")
    if(NOT EXISTS "${ROOT}/${path}")
        message(FATAL_ERROR "Missing vendored file: ${path}")
    endif()
    file(SHA256 "${ROOT}/${path}" actual)
    string(TOUPPER "${actual}" actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Vendored runtime modified: ${path}")
    endif()
    list(APPEND pinned "${path}")
endforeach()
list(SORT pinned)
if(NOT "${runtime}" STREQUAL "${pinned}")
    message(FATAL_ERROR "Incomplete dd runtime inventory (including templates)")
endif()
file(READ "${ROOT}/.gitattributes" attributes)
if(NOT attributes MATCHES "/dd\\.ps1 -text" OR NOT attributes MATCHES "/\\.dd/\\*\\* -text")
    message(FATAL_ERROR "Missing byte-stable dd checkout rules")
endif()
if(EXISTS "${ROOT}/dd.sh")
    message(FATAL_ERROR "Bespoke dd.sh must be retired")
endif()

if(BUILD_DIR)
    find_program(ctest NAMES ctest REQUIRED)
    foreach(scope all ci)
        set(filter)
        if(scope STREQUAL "ci")
            set(filter -L "^ci$")
        endif()
        execute_process(COMMAND "${ctest}" --test-dir "${BUILD_DIR}" --show-only=json-v1 ${filter}
            RESULT_VARIABLE result OUTPUT_VARIABLE listing ERROR_VARIABLE error)
        if(NOT "${result}" STREQUAL "0")
            message(FATAL_ERROR "CTest discovery failed: ${result}\n${error}")
        endif()
        string(JSON test_count LENGTH "${listing}" tests)
        math(EXPR test_last "${test_count} - 1")
        set(names)
        foreach(index RANGE ${test_last})
            string(JSON name GET "${listing}" tests ${index} name)
            list(APPEND names "${name}")
        endforeach()
        set(expected generated.dataset)
        set(prefixes generated)
        if(scope STREQUAL "all")
            set(have_dataset TRUE)
            foreach(split train test)
                set(path "${ROOT}/data/fashion-mnist_${split}.csv")
                if(EXISTS "${path}")
                    file(SIZE "${path}" bytes)
                    if(NOT bytes GREATER 1000000)
                        set(have_dataset FALSE)
                    endif()
                else()
                    set(have_dataset FALSE)
                endif()
            endforeach()
            if(have_dataset)
                list(APPEND prefixes dataset)
            endif()
        endif()
        foreach(prefix IN LISTS prefixes)
            foreach(case runs loads accuracy reproducible rejects-invalid-topology)
                list(APPEND expected "${prefix}.${case}")
            endforeach()
        endforeach()
        list(SORT expected)
        list(SORT names)
        if(NOT "${names}" STREQUAL "${expected}")
            message(FATAL_ERROR "Incorrect ${scope} CTest inventory: ${names}; expected ${expected}")
        endif()
    endforeach()
    message(STATUS "PASS exact CTest inventory and CI label filtering")
endif()
message(STATUS "PASS ${count} immutable dd files and byte-stable checkout rules")
